version: '3.8'

services:
  step-detection-api:
    build: .
    container_name: step-detection-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # Optional: Mount sample data if you want to update it without rebuilding
      - ./Sample Data:/app/Sample Data:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - step-detection-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: step-detection-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - step-detection-api
    restart: unless-stopped
    networks:
      - step-detection-network
    profiles:
      - production

networks:
  step-detection-network:
    driver: bridge
