# Step Detection Configuration

# Step Detection Configuration
detection:
  # Sensor buffer and thresholds
  window_size: 10 # Number of recent sensor readings to consider
  start_threshold: 0.3 # Threshold for step start detection
  end_threshold: 0.3 # Threshold for step end detection

  # Motion detection thresholds
  motion_threshold: 12.0 # Acceleration magnitude threshold for step detection
  gyro_threshold: 1.0 # Gyroscope magnitude threshold for step detection

  # Timing constraints
  min_step_interval: 0.8 # Minimum time (seconds) between step detections

  # Buffer settings
  processing_buffer_size: 100 # Size of processing times buffer

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  reload: true
  title: "Step Detection API"
  version: "2.0.0"

# Model Configuration (currently used values only)
model:
  input_shape: [6] # 6 sensor features (3 accel + 3 gyro)
  output_classes: 3 # No Label, Start, End

# Data Configuration
data:
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  model_save_path: "models"

# Debug Configuration
debug:
  enable_step_detection_logs: true
